This is makeindex, version 2.15 [TeX Live 2022/dev] (kpathsea + Thai support).
Scanning style file ./NeutrinoMagMomentTechnote.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file NeutrinoMagMomentTechnote.acn....done (313 entries accepted, 0 rejected).
Sorting entries.....done (2893 comparisons).
Generating output file NeutrinoMagMomentTechnote.acr....done (116 lines written, 0 warnings).
Output written in NeutrinoMagMomentTechnote.acr.
Transcript written in NeutrinoMagMomentTechnote.alg.
