This is makeindex, version 2.17 [TeX Live 2023] (kpathsea + Thai support).
Scanning style file ./NeutrinoMagMomentTechnote.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file NeutrinoMagMomentTechnote.acn....done (316 entries accepted, 0 rejected).
Sorting entries......done (3067 comparisons).
Generating output file NeutrinoMagMomentTechnote.acr....done (116 lines written, 0 warnings).
Output written in NeutrinoMagMomentTechnote.acr.
Transcript written in NeutrinoMagMomentTechnote.alg.
